# Generated by Django 4.1.7 on 2023-03-08 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menunode_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menunodetree',
            name='nearestAncestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nearest_ancestors', to='menu.menunode'),
        ),
    ]
